config/routes.rb
Rails.application.routes.draw do

  resources :orders, only:[:new, :create] do
    collection do
      post 'confirm'
    end
  end

  # 入力画面に戻った際のurlをusers/backではなく、users/newにするためにroutingを設定
  post 'orders/new', to:'orders#back'

  root to: 'albums#index'

  get 'home/flow', to: 'home#flow'

  # :controllersオプションで使用するコントローラを指定しています。
  # ちなみに'users/sessions'のusersはapp/controllers/usersディレクトリのことを表し、sessionsはsessions_controller.rbファイルの先頭を表しています。
  # そのため、実際のディレクトリ構造とファイル名とがこの設定と一致していないとうまく動きません。
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :albums do
    member do
      get 'show_for_order'
    end
  end

  namespace :admin do
    resources :orders do
      member do
        get 'user'
      end
    end
  end

  # ユーザー一覧ページ
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update_user', as: 'update_user'
  # ユーザーのマイページ
  get '/users/:id', to: 'users#show', as: 'show_users'
  get '/users/:id/schedule', to:'users#add_schedule', as: 'users_add_schedule'
  patch '/users/:id/update', to:'users#update', as: 'users_update_shcedule'
  get '/users/:id/schedule/index', to:'users#show_schedule', as: 'users_schedule'
  delete '/users/:id', to: 'users#destroy', as: 'users_destroy'

end

# After signing in a user, confirming the account or updating the password,
# Devise will look for a scoped root path to redirect to.
# For instance, when using a :user resource, the user_root_path will be used if it exists
# ; otherwise, the default root_path will be used. T
# his means that you need to set the root inside your routes:

# root to: 'home#index'
# You can also override after_sign_in_path_for and after_sign_out_path_for to customize your redirect hooks.

app/models/order.rb
class Order < ApplicationRecord
  validate :add_error_order
  after_update :send_email_update
  after_save :send_email

  # Railsの慣例では、相手のモデル上の外部キーを保持しているカラム名については、そのモデル名にサフィックス_idを追加した関連付け名が使用されることを前提としている。
  # :foreign_keyオプションを使用すると外部キーの名前を直接してすることができる。
  has_one :album, dependent: :destroy, inverse_of: :order
  belongs_to :area

  has_many :addtional_plans
  accepts_nested_attributes_for :addtional_plans

  belongs_to :user, optional: true

  private

  def send_email
    OrderMailer.post_order(@order).deliver_later
  end

  def send_email_update
    OrderMailer.photographer_post_order(@order).deliver_later
  end

  def add_error_order
    if first_name.blank?
      errors[:base] << "苗字は必ず入力してください"
    end

    if last_name.blank?
      errors[:base] << "名前は必ず入力してください"
    end

    if date.blank?
      errors[:base] << "日程は必ず入力してください"
    end

    if location.blank?
      errors[:base] << "場所を必ず入力してください"
    end

    if phone_number.blank?
      errors[:base] << "電話番号は必ず入力してください"
    end

    if email.blank?
      errors[:base] << "メールアドレスは必ず入力してください"
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:edit, :update, :destroy, :show]

  class InvalidPhotographerAssignment < StandardError; end

  def index
    @orders = Order.all
  end

  def show
  end

  def user
    @orders = Order.where(user_id: params[:id])
    render 'order_user'
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to admin_order_path, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # ①削除対象を見つける
    # ②削除
    @order.destroy
    # ③削除した後、戻りたい場所を指定
    redirect_to admin_orders_path, notice: 'Order was successfully destroyed'
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(
        :first_name,
        :last_name,
        :date,
        :location,
        :phone_number,
        :comment,
        :area_id,
        :photographer_id,
        :errors,
        :user_id,
        :email,
        addtional_plans_attributes: [:photo_number, :with_illustration]
      )
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @order.addtional_plans.build
  end

  def create
    @order = Order.new(order_params)
      #ActiveRecord::Base.transaction do
        # new: @order.areaでorderモデルに紐付いているareaを呼び出す
        # execute: photographersの配列を作成する
        # photographers = NeabyPhotographerService.new(@order.area).execute

        # 第一段階(計二段階中) - エリアによる絞り込み
    if @order.present?
      # @lはphotographerのorderと一致するdateの配列をphotographer_automatic_assignment_serviceにより格納するためのもの
      @l = PhotographerSearchService.new(@order).execute

      if @l.present?
        # tは配列の中からランダム抽出したもの
        t = @l.sample
        if current_user.present?
          @order.user_id = current_user.id
        end
        if @order.update(photographer_id: t.user_id)
          flash[:notice] = "申し込みが完了しました"
          redirect_to(root_path) and return
        else
          flash[:notice] = "申し込みに失敗しました"
          redirect_to(new_order_path)
        end
      else
        if current_user.present?
          @order.user_id = current_user.id
        end
        if @order.save
          flash[:notice] = "申し込みが完了しました"
          redirect_to(root_path) and return
        else
          flash[:notice] = "申し込みに失敗しました"
          redirect_to(new_order_path)
        end
      end
    else
      render :new
    end
  end

  def confirm
    @order = Order.new(order_params) # <= POSTされたパラメータを取得
    render :new if @order.invalid? #<= バリデーションチェックNGなら戻す
  end

  def back
    @order = Order.new(order_params)
    render :new
  end

  private

  def order_params
    params.require(:order).permit(
      :first_name,
      :last_name,
      :date,
      :location,
      :phone_number,
      :comment,
      :area_id,
      :photographer_id,
      :errors,
      :user_id,
      :email,
      addtional_plans_attributes: [:photo_number, :with_illustration]
    )
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.haml
= form_for @order, url: {:controller => :orders, :action => :confirm} do |f|
  .container
    .form-group
      = f.label :first_name
      = f.text_field :first_name, :class => "form-control", placeholder: "佐藤"
    .form-group
      = f.label :last_name
      = f.text_field :last_name , :class => "form-control", placeholder: "匠"
    .form-group
      = f.label :date
      = f.date_select :date , :class => "form-control"
    .form-group
      = f.label :location
      = f.text_field :location, :class => "form-control", placeholder: "自然の多い公園の近く"
    .form-group
      = f.label :phone_number
      = f.text_field :phone_number, :class => "form-control", placeholder: "08088889999"
    .form-group
      = f.label :area_id
      = f.collection_select :area_id, Area.all, :id, :prefecture, {prompt: "選択してください"}, {class: "form-control"}
    .form-group
      = f.label :comment
      = f.text_area :comment, :class => "form-control", placeholder: "楽しみにしています!"
    .form-group
      = f.fields_for :addtional_plans do |addtional_plan|
        = addtional_plan.label 'イラストオプション'
        = addtional_plan.select :with_illustration, [["イラストオプションを選択", false],["イラストオプションを追加する", true],["イラストオプションを追加しない", false]], :class => "form-control"
        = addtional_plan.label '写真追加オプション'
        = addtional_plan.select :photo_number, [["写真枚数を追加する場合は選択してください", 0],["1枚",1],["2枚", 2],["3枚", 3],["4枚", 4], ["5枚", 5]], :class => "form-control"

    = f.submit '申し込み確認画面へ', :class => "btn btn-primary"

app/views/admin/orders/_form2.html.haml
= form_for @order,  :url => {:controller => :orders, :action =>:update} do |f|
  .container
    .form-group
      = f.label :first_name
      = f.text_field :first_name, :class => "form-control", placeholder: "佐藤"
    .form-group
      = f.label :last_name
      = f.text_field :last_name , :class => "form-control", placeholder: "匠"
    .form-group
      = f.label :date
      = f.date_select :date , :class => "form-control"
    .form-group
      = f.label :location
      = f.text_field :location, :class => "form-control", placeholder: "自然の多い公園の近く"
    .form-group
      = f.label :email
      = f.text_field :email, :class => "form-control", placeholder: "hogehoge@example.com"
    .form-group
      = f.label :phone_number
      = f.text_field :phone_number, :class => "form-control", placeholder: "08088889999"
    - if current_user.admin?
      .form-group
        = f.label :photographer_id
        = f.collection_select :photographer_id, User.photographer.where(area_id: @order.area_id), :id, :email , {prompt: "選択してください"}, {class: "form-control"}
    .form-group
      = f.label :area_id
      = f.collection_select :area_id, Area.all, :id, :prefecture, {prompt: "選択してください"}, {class: "form-control"}
    .form-group
      = f.label :comment
      = f.text_area :comment, :class => "form-control", placeholder: "楽しみにしています!"
    .form-group
      = f.fields_for :addtional_plans do |addtional_plan|
        = addtional_plan.label 'イラストオプション'
        <br>
        = addtional_plan.select :with_illustration, [["イラストオプションを選択", false],["イラストオプションを追加する", true],["イラストオプションを追加しない", false]], :class => "form-control"
        <br>
        = addtional_plan.label '写真追加オプション'
        <br>
        = addtional_plan.select :photo_number, [["写真枚数を追加する場合は選択して下さい", 0],["1枚", 1], ["2枚", 2],["3枚", 3],["4枚", 4], ["5枚",5]], class: "form-control"
    = link_to '戻る', admin_orders_path,  class: 'btn btn-primary admin-botton'
    = f.submit "更新",:class => "btn btn-primary"

app/views/admin/orders/edit.html.haml
= render 'layouts/error'
.page-header
  %h1 編集フォーム
= render 'form2'

app/views/admin/orders/index.html.haml
.container-fluid
  .row
    %nav.col-md-2.d-none.d-md-block.bg-light.sidebar
      .sidebar-sticky
        %ul.nav.flex-column
          %li.nav-item
            = link_to 'ホームに戻る', root_path ,class: 'nav-link'
          %li.nav-item
            = link_to 'プロフィール編集', edit_user_registration_path ,class: 'nav-link'
          %li.nav-item
            = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'
          - if current_user.member?
            %li.nav-item
              = link_to '申し込み一覧', user_admin_order_path(current_user) , class: "nav-link"
          - unless current_user.member?
            %li.nav-item
              = link_to '依頼一覧', admin_orders_path , class: 'nav-link'
          - if current_user.photographer?
            %li.nav-item
              = link_to '予定入力', users_add_schedule_path(id: current_user.id), class: 'nav-link'
          - if current_user.admin?
            %li.nav-item
              = link_to 'ユーザー一覧', users_path ,class: 'nav-link'
    .col-md-10
      .page-header
      %h1 依頼一覧
      %table{:border => "1"}
        %tr
          %th id
          %th first_name
          %th last_name
          %th date
          %th location
          %th phone_number
          %th area
          %th photographer_id
          %th comment
          %th created_at
        - @orders.each do |order|
          %tr
            - if current_user.admin?
              %td= order.id
              %td= order.first_name
              %td= order.last_name
              %td= order.date
              %td= order.location
              %td= order.phone_number
              %td= order.area.prefecture
              %td= order.photographer_id
              %td= order.comment
              %td= order.created_at
              %td= link_to '詳細', admin_order_path(order) , :class => "btn btn-primary"
              %td= link_to '編集', edit_admin_order_path(order) , :class => "btn btn-primary"
              %td= link_to '削除', admin_order_path(order), :method => :delete, :confirm => "本当に削除していいですか?" , :class => "btn btn-primary"
            - if order.photographer_id == current_user.id
              %td= order.id
              %td= order.first_name
              %td= order.last_name
              %td= order.date
              %td= order.location
              %td= order.phone_number
              %td= order.area.prefecture
              %td= order.photographer_id
              %td= order.comment
              %td= order.created_at
              - if order.album.nil? && current_user.photographer? && current_user.id == order.photographer_id
                %td= link_to '納品', new_album_path(order: order) , :class => "btn btn-primary"
              %td= link_to '詳細', admin_order_path(order) , :class => "btn btn-primary"

app/views/admin/orders/order_user.html.haml
.container-fluid
  .row
    %nav.col-md-2.d-none.d-md-block.bg-light.sidebar
      .sidebar-sticky
        %ul.nav.flex-column
          %li.nav-item
            = link_to 'ホームに戻る', root_path ,class: 'nav-link'
          %li.nav-item
            = link_to 'プロフィール編集', edit_user_registration_path ,class: 'nav-link'
          %li.nav-item
            = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'
          - if current_user.member?
            %li.nav-item
              = link_to '申し込み一覧', user_admin_order_path , class: "nav-link"
          - if current_user.photographer?
            %li.nav-item
              = link_to '依頼一覧', admin_orders_path , class: 'nav-link'
            %li.nav-item
              = link_to '予定入力', users_add_schedule_path(id: current_user.id), class: 'nav-link'
          - if current_user.admin?
            %li.nav-item
              = link_to 'ユーザー一覧', users_path ,class: 'nav-link'
    .col-md-10
      .page-header
      %h1 申込一覧
      %table{:border => "1"}
        %tr
          %th id
          %th first_name
          %th last_name
          %th date
          %th location
          %th phone_number
          %th area
          %th photographer_id
          %th comment
          %th created_at
        - @orders.each do |order|
          %tr
            %td= order.id
            %td= order.first_name
            %td= order.last_name
            %td= order.date
            %td= order.location
            %td= order.phone_number
            %td= order.area.prefecture
            %td= order.photographer_id
            %td= order.comment
            %td= order.created_at
            %td= link_to '詳細', admin_order_path(order) , :class => "btn btn-primary"

app/views/admin/orders/show.html.haml
.signup-page
  %h2.explanation-text 依頼詳細
  .formContainer
    %table.table-order{:border => "1"}
      %tr
        %th id
        %td= @order.id
      %tr
        %th first_name
        %td= @order.first_name
      %tr
        %th last_name
        %td= @order.last_name
      %tr
        %th date
        %td= @order.date
      %tr
        %th location
        %td= @order.location
      %tr
        %th phone_number
        %td= @order.phone_number
      %tr
        %th photographer_id
        %td= @order.photographer_id
      %tr
        %th comment
        %td= @order.comment
      %tr
        %th created_at
        %td= @order.created_at
      %tr
        %th user_id
        - unless @order.user_id.nil?
          %td= @order.user_id
        - else
          %td
    - if @order.album.present?
      %table.container
        %th
          %td= link_to image_tag(@order.album.photographs[0].url(:thumb)), show_for_order_album_path
    - if current_user.member?
      = link_to '戻る', user_admin_order_path(current_user), class: 'btn btn-primary admin-botton'
    - else
      = link_to '戻る', admin_orders_path, class: 'btn btn-primary admin-botton'
    - if current_user.admin?
      = link_to '編集', edit_admin_order_path(@order), class: 'btn btn-primary admin-botton'
      = link_to '削除', admin_order_path(@order), :method => :delete, :confirm => "本当に削除していいですか", class: 'btn btn-primary admin-botton'