config/routes.rb
Rails.application.routes.draw do

  resources :orders, only:[:new, :create] do
    collection do
      post 'confirm'
    end
  end

  # 入力画面に戻った際のurlをusers/backではなく、users/newにするためにroutingを設定
  post 'orders/new', to:'orders#back'

  root to: 'albums#index'

  get 'home/flow', to: 'home#flow'

  # :controllersオプションで使用するコントローラを指定しています。
  # ちなみに'users/sessions'のusersはapp/controllers/usersディレクトリのことを表し、sessionsはsessions_controller.rbファイルの先頭を表しています。
  # そのため、実際のディレクトリ構造とファイル名とがこの設定と一致していないとうまく動きません。
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :albums do
    member do
      get 'show_for_order'
    end
  end

  namespace :admin do
    resources :orders do
      member do
        get 'user'
      end
    end
  end

  # ユーザー一覧ページ
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update_user', as: 'update_user'
  # ユーザーのマイページ
  get '/users/:id', to: 'users#show', as: 'show_users'
  get '/users/:id/schedule', to:'users#add_schedule', as: 'users_add_schedule'
  patch '/users/:id/update', to:'users#update', as: 'users_update_shcedule'
  get '/users/:id/schedule/index', to:'users#show_schedule', as: 'users_schedule'
  delete '/users/:id', to: 'users#destroy', as: 'users_destroy'

end

# After signing in a user, confirming the account or updating the password,
# Devise will look for a scoped root path to redirect to.
# For instance, when using a :user resource, the user_root_path will be used if it exists
# ; otherwise, the default root_path will be used. T
# his means that you need to set the root inside your routes:

# root to: 'home#index'
# You can also override after_sign_in_path_for and after_sign_out_path_for to customize your redirect hooks.

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  validate :add_error_order
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: {admin: 1, photographer: 2, member: 3 }

  has_many :schedules
  has_many :orders, dependent: :destroy
  belongs_to :area, optional: true

  # Scope
  scope :search_area, ->(area_id){ where(area_id: area_id )}
  # あとで、orders_controller.rb(本当はserviceディレクトリの中のAutomatingのところにあるやつ)で、
  #.where(area_id: @area.id)を.search_area(@area.id)に書き換えたら、
  # このコメントは削除する

  # accepts_nested_attributes_forは、親子関係のある関連モデル(Project has_many :tasks や Enquate has_many :questionsなど)で、親から子を作成したり保存したりする時に使える。。
  accepts_nested_attributes_for :schedules


  private

  def add_error_order
    if email.blank?
      errors[:base] << "emailは必ず入力してください"
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true
# ユーザー登録確認メール内のリンクを押した時につかう

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true
# パスワードを忘れ方は。。。の場合に使う

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
# ユーザー登録をする時に使う

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    DeviceMailer.new_user_registraion.deliver_later
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  #PUT /resource
  # def update
  #   self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
  #   prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
  #
  #   resource_updated = update_resource(resource, account_update_params)
  #   yield resource if block_given?
  #   if resource_updated
  #     if is_flashing_format?
  #       flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
  #         :update_needs_confirmation : :updated
  #       set_flash_message :notice, flash_key
  #     end
  #     bypass_sign_in resource, scope: resource_name
  #     respond_with resource, location: after_update_path_for(resource)
  #   else
  #     clean_up_passwords resource
  #     set_minimum_password_length
  #     respond_with resource
  #   end
  # end
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  #
  private

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #　  devise_parameter_sanitizer.permit(:account_update, keys: [:attribute], :area_id)
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

    def after_update_path_for(resource)
      if current_user.member?
        root_path
      else
        show_users_path(resource)
      end
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
# ログインをする時に使う。

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_user
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path, notice: 'User was updated!'
  end

  def destroy
    # ①削除対象を見つける
    @user = User.find(params[:id])
    # ②削除
    @user.destroy
    # ③削除した後、戻りたい場所を指定
    redirect_to users_path, notice: 'User was successfully destroyed'
  end

  def show
    @user = User.find(params[:id])
  end

  def add_schedule
    @user = User.find(params[:id])
    30.times do
      @user.schedules.build
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "スケジュールを更新しました。"
    redirect_to show_users_path(id: params[:id])
  end

  def show_schedule
    @schedules = Schedule.where(user_id: params[:id])
  end

  private
    def user_params
      params.require(:user).permit(
        :email,
        :encrypted_password,
        :role,
        :order_id,
        schedules_attributes: [:target_day, :status]
      )
    end
end

# timseメソッド
# オブジェクト.times{ |変数|
#   実行する処理1
#   実行sする処理2
# }

# オブジェクト.times do |変数|
#   実行する処理1
#   実行する処理2
# end

# timesメソッドは、変数に「０」から「対象のオブジェクトが持つ数値−１」を順に代入しながら「{」から「}」までの処理を実行します。
# 1回繰り返す毎に１ずつ数値は増加します。「｜変数｜の部分は省略可能です。」

#  具体的には次のようにします
# 10.times {
#   print("Hello\n")
# }
# 上記の場合は10回「{」から「}」までの処理を繰り返します。

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_adminpage.html.erb
<p>admin information</p>

app/views/users/_photographerpage.html.erb
<p>photographer page</p>

app/views/users/_userpage.html.erb
<p>member information</p>

app/views/users/add_schedule.html.erb
<!-- value：コントロールの初期値です。この属性はtype属性の値がradioまたはcheckboxである場合を除き、省略可能です。
    ページを再読み込みするとき、GeckkoおよびIEは再読み込み前に値が変更された場合にHTMLソースで指定された値を無視する点には注意 -->
<div class="container">
<div class="row">
<h2>予定入力</h2>
<%= form_for @user, url: {action: :update} do |f| %>
  <% day = Date.today %>
  <% i = 0 %>

  <%= f.hidden_field :email %>
  <%= f.hidden_field :encrypted_password %>
  <%= f.hidden_field :role %>

  <%= f.fields_for :schedules  do |schedule_form| %>
  <% if day < ( Date.today >> 1 ) %>
    <div class="field">
      <%= schedule_form.label day %>
      <%= schedule_form.hidden_field :target_day, :value => day %>
    </div>
    <div class="field">
      <%= schedule_form.label '行ける・行けないを選択' %>
      <% if current_user.schedules.where(target_day: Date.today + i).present? %>
        <label><%= schedule_form.radio_button :status,true,{checked: current_user.schedules.where(target_day: Date.today + i).last.status } %> 行ける </label>
      <% else %>
        <label><%= schedule_form.radio_button :status,true  %> 行ける </label>
      <% end %>
      <% if current_user.schedules.where(target_day: Date.today + i).present? %>
        <label><%= schedule_form.radio_button :status,false ,{checked: !current_user.schedules.where(target_day: Date.today + i).last.status }%> 行けない </label>
      <% else %>
        <label><%= schedule_form.radio_button :status,false %> 行けない </label>
      <% end %>
      <% i += 1 %>
      <% day += 1 %>
    </div>
  <% end %>
  <% end %>

  <%= f.submit 'Save' %>
<% end %>
</div>
</div>

<!-- radio_buttonのchecked,trueは、
　　　フォームを作成するケースで元からチェックを入れたい(チェック済み)場合、確認画面から戻ってきたときにチェックがあらかじめ入っている処理にしたい場合に利用する -->

<!-- [Ruby on Railsでform_forでラジオボタンを設置する方法](http://freesworder.net/rails-form_for-radio/) -->
<!-- @user.schedules[0].status -->

app/views/users/edit.html.erb
<div class="signup-page" >
<h2 class="explanation-text">プロフィール編集画面</h2>
<%= render 'layouts/error' %>
<div class="formContainer">
<%= form_for @user,  url: {:controller => :users, :action => :update_user} do |f| %>
  <div class="field form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" , placeholder: "hoge@example.com"%>
  </div>

  <div class="field form-group">
    <%= f.label :role %><br />
    <%= f.select :role ,{'administer' => 'admin','photographer' => 'photographer', 'member' => 'member'}, :include_blank => false, autofocus: true, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= f.submit "更新" , :class => "btn btn-primary" %>
  </div>
<% end %>

<h2 class="explanation-text">アカウントの削除</h2>

<p><%= link_to "このアカウントを削除する", users_destroy_path(@user), data: { confirm: "Are you sure?" }, method: :delete, :class => "btn btn-primary" %></p>

<%= link_to "戻る", users_path, :class => "btn btn-primary"%>
</div>
</div>

app/views/users/index.html.haml
.classcontainer-fluid
  .row
    %nav.col-md-2.d-none.d-md-block.bg-light.sidebar
      .sidebar-sticky
        %ul.nav.flex-column
          %li.nav-item
            = link_to 'ホームに戻る', root_path ,class: 'nav-link'
          %li.nav-item
            = link_to 'プロフィール編集', edit_user_registration_path ,class: 'nav-link'
          %li.nav-item
            = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'
          - if current_user.member?
            %li.nav-item
              = link_to '申し込み一覧', user_admin_order_path(current_user) , class: "nav-link"
          - unless current_user.member?
            %li.nav-item
              = link_to '依頼一覧', admin_orders_path , class: 'nav-link'
          - if current_user.photographer?
            %li.nav-item
              = link_to '予定入力', users_add_schedule_path(id: current_user.id), class: 'nav-link'
          - if current_user.admin?
            %li.nav-item
              = link_to 'ユーザー一覧', users_path ,class: 'nav-link'
.col-md-10.user_index
  .page-header
    %h2 ユーザー一覧
    <br/>
    %table{:border => "1"}
      %tr
        %th id
        %th email
        %th role
      - @users.each do |user|
        %tr
          %td= user.id
          %td= user.email
          %td= user.role
          %td= link_to 'roleの変更',edit_user_path(user) , :class => "btn btn-primary"
          %td= link_to '削除', users_destroy_path(user), :method => :delete, data:{:confirm => "本当に削除していいですか?"} , :class => "btn btn-primary"

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
          <%= link_to 'ホームに戻る', root_path ,class: 'nav-link' %>
          </li>
          <li class="nav-item">
          <%= link_to 'プロフィール編集', edit_user_registration_path ,class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'%>
          </li>
          <% unless current_user.member? %>
            <li class="nav-item">
              <%= link_to '依頼一覧', admin_orders_path , class: "nav-link"%>
            </li>
          <% end %>
          <% if current_user.photographer? %>
            <li class="nav-item">
              <%= link_to '予定入力', users_add_schedule_path(id: @user.id), class: "nav-link" %>
            </li>
          <% end %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', users_path ,class: 'nav-link' %>
            </li>
          <% end %>
          <% if current_user.member? %>
            <li class="nav-item">
              <%= link_to '申し込み一覧', user_admin_order_path(id: @user.id), class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="col-md-10">
      <% if current_user.member? %>
        <%= render 'userpage' %>
      <% elsif current_user.photographer? %>
        <%= render 'photographerpage' %>
      <% else %>
        <%= render 'adminpage' %>
      <% end %>
    </div>
  </div>
</div>