config/routes.rb
Rails.application.routes.draw do

  resources :orders, only:[:new, :create] do
    collection do
      post 'confirm'
    end
  end

  # 入力画面に戻った際のurlをusers/backではなく、users/newにするためにroutingを設定
  post 'orders/new', to:'orders#back'

  root to: 'albums#index'

  get 'home/flow', to: 'home#flow'

  # :controllersオプションで使用するコントローラを指定しています。
  # ちなみに'users/sessions'のusersはapp/controllers/usersディレクトリのことを表し、sessionsはsessions_controller.rbファイルの先頭を表しています。
  # そのため、実際のディレクトリ構造とファイル名とがこの設定と一致していないとうまく動きません。
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :albums do
    member do
      get 'show_for_order'
    end
  end

  namespace :admin do
    resources :orders do
      member do
        get 'user'
      end
    end
  end

  # ユーザー一覧ページ
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update_user', as: 'update_user'
  # ユーザーのマイページ
  get '/users/:id', to: 'users#show', as: 'show_users'
  get '/users/:id/schedule', to:'users#add_schedule', as: 'users_add_schedule'
  patch '/users/:id/update', to:'users#update', as: 'users_update_shcedule'
  get '/users/:id/schedule/index', to:'users#show_schedule', as: 'users_schedule'
  delete '/users/:id', to: 'users#destroy', as: 'users_destroy'

end

# After signing in a user, confirming the account or updating the password,
# Devise will look for a scoped root path to redirect to.
# For instance, when using a :user resource, the user_root_path will be used if it exists
# ; otherwise, the default root_path will be used. T
# his means that you need to set the root inside your routes:

# root to: 'home#index'
# You can also override after_sign_in_path_for and after_sign_out_path_for to customize your redirect hooks.

app/views/layouts/_error.html.erb
<% if @order.nil? %>
<% elsif @order.errors.any? %>
  <div class="error_explanation">
    <h2><%= @order.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="global-nav">
    <ul>
      <li class="nav-item">
        <%= link_to 'lovegraph', root_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'flow', home_flow_path %>
      </li>
      <li class="nav-item">
        <%= link_to '申し込み', orders_new_path %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'プロフィール編集', edit_user_registration_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to 'マイページへ', show_users_path(current_user.id) %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to '新規登録', new_user_registration_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログイン', new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Takugraph
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    - flash.each do |key, value|
      %div{:class => "alert alert-#{key}"}
        = value
    = yield